blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions
    url: https://github.com/originzero-io/originzero/discussions
    about: Please ask and answer questions in the discussions section
  - name: 💬 Discord
    url: https://discord.gg/uRJUjWvH
    about: Chat about the project on our discord community
