name: ⭐️ Feature Request
description: Suggest a new feature or idea for originzero low-code automation tool
labels: feature request
body:
  - type: textarea
    id: description
    attributes:
      label: Please describe the feature that you want to propose
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
